bag_login_web_social:
    pattern: /login/{network}
    defaults: { _controller: BagLoginBundle:Social:getSocialToken, _format:json }
    requirements:
        network:  facebook|google|twitter

bag_login_web_page_not_found:
    pattern: /pageNotFound
    defaults: { _controller: BagLoginBundle:Default:pageNotFound }
    requirements:
        _method:  GET
        
# Registration

bag_login_web_request_activation_email:
    pattern:  /request/activation/email
    defaults: { _controller: BagLoginBundle:Registration:requestActivationEmail }
    requirements:
        _method:  GET|POST

bag_login_web_request_activation_email_completed:
    pattern:  /activation/email/sent
    defaults: { _controller: BagLoginBundle:Registration:requestActivationEmailCompleted }
    requirements:
        _method:  GET

bag_login_web_register:
    pattern:  /register
    defaults: { _controller: BagLoginBundle:Registration:register }
    requirements:
        _method:  GET|POST

bag_login_web_registration_completed:
    pattern:  /registration/done
    defaults: { _controller: BagLoginBundle:Registration:registrationCompleted }
    requirements:
        _method:  GET|POST

bag_login_web_account_activation:
    pattern:  /activate/account/{token}
    defaults: { _controller: BagLoginBundle:Registration:accountActivation }
    requirements:
        _method:  GET

bag_login_web_account_activation_completed:
    pattern:  /account/activated
    defaults: { _controller: BagLoginBundle:Registration:accountActivationCompleted }
    requirements:
        _method:  GET

# Login

bag_login_web_login:
    pattern:  /login
    defaults: { _controller: BagLoginBundle:Security:login }
    requirements:
        _method:  GET

bag_login_web_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    requirements:
        _method:  GET

bag_login_web_login_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method:  POST

# Password reset

bag_login_web_password_reset:
    pattern:  /request/new/password
    defaults: { _controller: BagLoginBundle:Password:requestNew }
    requirements:
        _method:  GET|POST

bag_login_web_password_reset_done:
    pattern:  /request/new/password/completed
    defaults: { _controller: BagLoginBundle:Password:requestCompleted }
    requirements:
        _method:  GET

bag_login_web_change_password:
    pattern:  /change/password/{token}
    defaults: { _controller: BagLoginBundle:Password:change }
    requirements:
        _method:  GET|POST

bag_login_web_change_password_done:
    pattern:  /change/password/completed
    defaults: { _controller: BagLoginBundle:Password:changeCompleted }
    requirements:
        _method:  GET
