bag_login_api_social:
    pattern: /login/{network}
    defaults: { _controller: BagLoginBundle:API:getSocialToken, _format:json }
    requirements:
        _method:  POST
        network:  facebook|google|twitter

# Registration

bag_login_api_request_activation_email:
    pattern:  /request/activation/email
    defaults: { _controller: BagLoginBundle:API:requestActivationEmail, _format:json }
    requirements:
        _method:  POST

bag_login_api_register:
    pattern:  /register
    defaults: { _controller: BagLoginBundle:API:register, _format:json }
    requirements:
        _method:  POST

# Password reset

bag_login_api_password_reset:
    pattern:  /request/new/password
    defaults: { _controller: BagLoginBundle:API:requestNewPassword, _format:json }
    requirements:
        _method:  POST
